services:
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: mypicsdb3
      MARIADB_USER: mypicsdb3
      MARIADB_PASSWORD: mypicsdb3
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 3s
      retries: 20
